variable vpc_cidr_block {}
variable env_prefix {}
variable az {}
variable region {}
variable my_ip {}
variable instance_type {}
variable public_key_location {}
variable subnet_cidr_block {}
variable image_name {}